%YAML:1.0
---
LoaderColorCamera:
   -
      name: loader_color
      metafile_path: "camera_color.yaml"
NormalColorViewer:
   -
      name: color_viewer
      color_camera: loader_color
      renderer_geometry: renderer_geometry
RendererGeometry:
   -
      name: renderer_geometry
      bodies:
         - cracker_box
Body:
   -
      name: cracker_box
      metafile_path: "object.yaml"
NetworkDetector:
   -
      name: network_detector
      metafile_path: "detector.yaml"
      body: cracker_box
      color_camera: loader_color
RegionModel:
   -
      name: region_model
      metafile_path: "model.yaml"
      body: cracker_box
RegionModality:
   -
      name: region_modality
      body: cracker_box
      color_camera: loader_color
      region_model: region_model
      metafile_path: "region_modality.yaml"
      measure_occlusions:
         depth_camera: loader_depth
LoaderDepthCamera:
   -
      name: loader_depth
      metafile_path: "camera_depth.yaml"
NormalDepthViewer:
   -
      name: depth_viewer
      depth_camera: loader_depth
      renderer_geometry: renderer_geometry
DepthModel:
   -
      name: depth_model
      metafile_path: "model.yaml"
      body: cracker_box
DepthModality:
   -
      name: depth_modality
      body: cracker_box
      depth_camera: loader_depth
      depth_model: depth_model
      metafile_path: "depth_modality.yaml"
FeatureViewer:
   -
      name: feature_viewer
      color_camera: loader_color
      renderer_geometry: renderer_geometry
FeatureModel:
   -
      name: feature_model
      metafile_path: "model.yaml"
      body: cracker_box
FeatureModality:
   -
      name: feature_modality
      body: cracker_box
      color_camera: loader_color
      depth_camera: loader_depth
      feature_model: feature_model
      metafile_path: "feature_modality.yaml"
Optimizer:
   -
      name: optimizer
      modalities:
         - region_modality
         - depth_modality
         - feature_modality
Tracker:
   -
      name: tracker
      viewers:
         - color_viewer
         - depth_viewer
      detectors:
         - network_detector
      optimizers:
         - optimizer
